### ISSUE TITLE
Image for gts4lvwifi

### ISSUE THREAD

**Issue by lohriialo** [SINARIS-GH/firmware-device_samsung_gts4lvwifiaaos#1]
Is there a build image we can try for gts4lvwifiaaos

**Comment by GRTWOSTEP** [comment]
Hi,
There's a build but Bluetooth doesn't work correctly

**Comment by GRTWOSTEP** [comment]
**Build (Android11, LineageOS18.1, gts4lvwifi)**
Self hosting (st4g3.fr is mine)

- [aaos11.zip](http://st4g3.fr:8888/down/XtxjGiqcmovh)

**Google Apps (Android11)**

- [gapps.zip](http://st4g3.fr:8888/down/rFIuWYKDZqjE)

**Comment by lohriialo** [comment]
Thanks, we'll give it a try
